"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Building2, Filter, Plus, Search, X } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ApplicationMobileCard } from "@/components/application-mobile-card";
import { EmptyState, InlineErrorState, PageLoadingState } from "@/components/async-state";
import { PageHeader } from "@/components/page-header";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/formatters";
import { formatRiskScoreBadge, loanTypeLabel, riskDisplay } from "@/lib/risk-display";

const loanLabels = { all: "All loan types", purchase: "Owner-occupier purchase", investment: "Investment purchase", refinance: "Refinance", first_home: "First home buyer", self_employed: "Self-employed" };
const statusLabels = { all: "All statuses", draft: "Draft", in_review: "In review", approved: "Approved", rejected: "Rejected" };
const sortLabels = { desc: "Newest first", asc: "Oldest first" };
function statusClass(status) { return status === "approved" ? "border-emerald-300 bg-emerald-50 text-emerald-700" : status === "rejected" ? "border-red-300 bg-red-50 text-red-700" : status === "in_review" ? "border-amber-300 bg-amber-50 text-amber-700" : "border-slate-300 bg-slate-100 text-slate-700"; }
function crmLabel(app) { if (app.crm_application_id) return `Synced · ${app.crm_application_id}`; if (app.crm_sync_status === "failed" || app.crm_sync_status === "failed_permanent") return "Sync failed"; if (app.crm_sync_status === "pending") return "Queued"; if (app.crm_sync_status === "in_progress") return "Syncing"; return "Not linked"; }

export default function ApplicationsPage() {
  const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [searchQuery, setSearchQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [loanTypeFilter, setLoanTypeFilter] = useState("all"); const [dateSortOrder, setDateSortOrder] = useState("desc");
  async function load() { setLoading(true); setError(""); try { const response = await api.getSubmissions(); setApplications(response.data || []); } catch (e) { setError(e.message || "Applications could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { void (async () => { try { const response = await api.getSubmissions(); setApplications(response.data || []); } catch (e) { setError(e.message || "Applications could not be loaded."); } finally { setLoading(false); } })(); }, []);
  const filtered = useMemo(() => applications.filter((app) => { const q = searchQuery.trim().toLowerCase(); const haystack = [app.id, app.local_application_id, app.crm_application_id, app.customer_name].filter(Boolean).join(" ").toLowerCase(); return (!q || haystack.includes(q)) && (statusFilter === "all" || app.submission_status === statusFilter) && (loanTypeFilter === "all" || app.loan_type === loanTypeFilter); }).sort((a,b) => dateSortOrder === "asc" ? new Date(a.created_at) - new Date(b.created_at) : new Date(b.created_at) - new Date(a.created_at)), [applications, searchQuery, statusFilter, loanTypeFilter, dateSortOrder]);
  const hasFilters = Boolean(searchQuery || statusFilter !== "all" || loanTypeFilter !== "all" || dateSortOrder !== "desc"); const clear = () => { setSearchQuery(""); setStatusFilter("all"); setLoanTypeFilter("all"); setDateSortOrder("desc"); };
  return <div className="mx-auto w-full max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Applications" title="Applications" description="Search, review and manage mortgage applications." actions={<Link href="/applications/new"><Button className="w-full bg-blue-600 hover:bg-blue-700"><Plus className="mr-1.5 h-4 w-4" />New application</Button></Link>} />
    <Card className="rounded-xl border-slate-200 shadow-sm"><CardContent className="space-y-4 p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input className="h-10 pl-9" placeholder="Search applicant, local ID or CRM ID…" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} /></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-3 lg:flex"><Select value={loanTypeFilter} onValueChange={setLoanTypeFilter}><SelectTrigger className="h-10 w-full min-w-40"><Filter className="mr-2 h-4 w-4 text-slate-400" /><SelectValue>{loanLabels[loanTypeFilter]}</SelectValue></SelectTrigger><SelectContent>{Object.entries(loanLabels).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="h-10 w-full min-w-36"><SelectValue>{statusLabels[statusFilter]}</SelectValue></SelectTrigger><SelectContent>{Object.entries(statusLabels).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={dateSortOrder} onValueChange={setDateSortOrder}><SelectTrigger className="h-10 w-full min-w-36"><SelectValue>{sortLabels[dateSortOrder]}</SelectValue></SelectTrigger><SelectContent>{Object.entries(sortLabels).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div></div><div className="flex items-center justify-between gap-3"><p className="text-sm text-slate-500">{filtered.length} {filtered.length === 1 ? "application" : "applications"}{hasFilters ? ` of ${applications.length}` : ""}</p>{hasFilters && <Button type="button" variant="ghost" size="sm" onClick={clear}><X className="mr-1 h-3.5 w-3.5" />Clear filters</Button>}</div></CardContent></Card>
    {loading ? <PageLoadingState label="Loading applications…" /> : error ? <InlineErrorState title="Applications could not be loaded" message={error} onRetry={load} /> : filtered.length === 0 ? <EmptyState title={applications.length ? "No applications match these filters" : "No applications yet"} message={applications.length ? "Try clearing a filter or adjusting your search." : "Create an application to begin the review workflow."} action={applications.length ? <Button variant="outline" onClick={clear}>Clear filters</Button> : <Link href="/applications/new"><Button>New application</Button></Link>} /> : <Card className="overflow-hidden rounded-xl border-slate-200 shadow-sm"><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Application</TableHead><TableHead>Applicant</TableHead><TableHead>Loan type</TableHead><TableHead>Submitted</TableHead><TableHead>Status</TableHead><TableHead>Risk</TableHead><TableHead>CRM</TableHead><TableHead className="text-right"> </TableHead></TableRow></TableHeader><TableBody>{filtered.map((app) => { const badge = formatRiskScoreBadge(app); const risk = riskDisplay(app.risk_level); return <TableRow key={app.id} className="hover:bg-slate-50/80"><TableCell><p className="font-mono text-xs font-semibold text-slate-900">{app.local_application_id || app.id}</p><p className="mt-1 text-xs text-slate-500">{app.source_channel === "crm" ? "Mercury CRM intake" : "Manual intake"}</p></TableCell><TableCell className="font-medium text-slate-950">{app.customer_name}</TableCell><TableCell>{loanTypeLabel(app.loan_type)}</TableCell><TableCell>{formatDate(app.created_at)}</TableCell><TableCell><Badge variant="outline" className={statusClass(app.submission_status)}>{String(app.submission_status || "draft").replace("_", " ")}</Badge></TableCell><TableCell><Badge variant="outline" className={badge.className}>{badge.scoreText != null ? `${badge.scoreText} · ${risk.label}` : badge.label}</Badge></TableCell><TableCell><span className="flex max-w-44 items-center gap-1.5 truncate text-xs text-slate-600"><Building2 className="h-3.5 w-3.5 shrink-0 text-slate-400" />{crmLabel(app)}</span></TableCell><TableCell className="text-right"><Link href={`/application/${app.id}`} className="inline-flex items-center text-sm font-medium text-blue-700 hover:text-blue-800">Review <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></TableCell></TableRow>; })}</TableBody></Table></div><div className="space-y-3 p-4 md:hidden">{filtered.map((app) => <ApplicationMobileCard key={app.id} app={app} showCrm />)}</div></Card>}</div>;
}
