"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, Plus } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/page-header";
import { MetricCard } from "@/components/metric-card";
import { ApplicationMobileCard } from "@/components/application-mobile-card";
import { EmptyState, InlineErrorState, PageLoadingState } from "@/components/async-state";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/formatters";
import { formatRiskScoreBadge, loanTypeLabel, riskDisplay } from "@/lib/risk-display";

function statusClass(status) { return status === "approved" ? "border-emerald-300 bg-emerald-50 text-emerald-700" : status === "rejected" ? "border-red-300 bg-red-50 text-red-700" : status === "in_review" ? "border-amber-300 bg-amber-50 text-amber-700" : "border-slate-300 bg-slate-100 text-slate-700"; }

export default function DashboardPage() {
  const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function loadApplications() { setLoading(true); setError(""); try { const response = await api.getSubmissions(); setApplications(response.data || []); } catch (e) { setError(e.message || "Applications could not be loaded."); } finally { setLoading(false); } }
  useEffect(() => { void (async () => { try { const response = await api.getSubmissions(); setApplications(response.data || []); } catch (e) { setError(e.message || "Applications could not be loaded."); } finally { setLoading(false); } })(); }, []);
  const recent = useMemo(() => [...applications].sort((a,b) => new Date(b.created_at) - new Date(a.created_at)).slice(0,5), [applications]);
  const metrics = { total: applications.length, pending: applications.filter((a) => a.submission_status === "in_review").length, high: applications.filter((a) => a.risk_level === "high").length, approved: applications.filter((a) => a.submission_status === "approved").length };
  return <div className="mx-auto w-full max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Workspace overview" title="Dashboard" description="Monitor application review, risk and approval activity." actions={<Link href="/applications/new"><Button className="w-full bg-blue-600 hover:bg-blue-700"><Plus className="mr-1.5 h-4 w-4" />New application</Button></Link>} />
    {loading ? <PageLoadingState label="Loading workspace overview…" /> : error ? <InlineErrorState title="Dashboard could not be loaded" message={error} onRetry={loadApplications} /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total applications" value={metrics.total} hint="All applications in the workspace" icon={FileText} tone="info" /><MetricCard label="Pending review" value={metrics.pending} hint="Applications requiring a decision" icon={Clock3} tone="warning" /><MetricCard label="High risk" value={metrics.high} hint="Applications needing close attention" icon={AlertTriangle} tone="danger" /><MetricCard label="Approved" value={metrics.approved} hint="Ready for the next workflow step" icon={CheckCircle2} tone="success" /></section>
      <Card className="rounded-xl border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between border-b border-slate-100 px-5 py-4"><div><CardTitle className="text-base font-semibold text-slate-900">Recent applications</CardTitle><p className="mt-1 text-sm text-slate-500">Latest five submissions</p></div><Link href="/applications" className="hidden sm:block"><Button variant="ghost" size="sm">View all <ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></Link></CardHeader><CardContent className="p-0">{recent.length === 0 ? <div className="p-5"><EmptyState title="No applications yet" message="Create your first application to begin the review workflow." action={<Link href="/applications/new"><Button>New application</Button></Link>} /></div> : <><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead className="pl-5">Applicant</TableHead><TableHead>Application</TableHead><TableHead>Loan type</TableHead><TableHead>Submitted</TableHead><TableHead>Status</TableHead><TableHead>Risk</TableHead><TableHead className="pr-5 text-right"> </TableHead></TableRow></TableHeader><TableBody>{recent.map((app) => { const badge = formatRiskScoreBadge(app); const risk = riskDisplay(app.risk_level); return <TableRow key={app.id} className="hover:bg-slate-50/80"><TableCell className="pl-5 font-medium text-slate-950">{app.customer_name}</TableCell><TableCell className="font-mono text-xs text-slate-500">{app.local_application_id || app.id}</TableCell><TableCell>{loanTypeLabel(app.loan_type)}</TableCell><TableCell>{formatDate(app.created_at)}</TableCell><TableCell><Badge variant="outline" className={statusClass(app.submission_status)}>{String(app.submission_status || "draft").replace("_", " ")}</Badge></TableCell><TableCell><Badge variant="outline" className={badge.className}>{badge.scoreText != null ? `${badge.scoreText} · ${risk.label}` : badge.label}</Badge></TableCell><TableCell className="pr-5 text-right"><Link href={`/application/${app.id}`} className="text-sm font-medium text-blue-700 hover:text-blue-800">Review</Link></TableCell></TableRow>; })}</TableBody></Table></div><div className="space-y-3 p-4 md:hidden">{recent.map((app) => <ApplicationMobileCard key={app.id} app={app} />)}<Link href="/applications" className="block"><Button variant="outline" className="w-full">View all applications</Button></Link></div></>}</CardContent></Card></>}</div>;
}
